# Generated by Django 4.0.4 on 2022-05-31 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professors',
            field=models.ManyToManyField(related_name='professors', to=settings.AUTH_USER_MODEL),
        ),
    ]
