# Generated by Django 4.0.4 on 2022-06-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_professors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_no', models.IntegerField(default=1)),
                ('lab_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_due', models.DateTimeField(blank=True)),
                ('description', models.TextField()),
                ('tutorials', models.FileField(blank=True, upload_to='tutorials/lab_<django.db.models.fields.IntegerField>/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
