# Generated by Django 4.0.4 on 2022-06-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lab_date_due_alter_lab_tutorials'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
