# Generated by Django 4.0.4 on 2022-06-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lab_date_due_alter_lab_tutorials'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=12345, max_length=5),
            preserve_default=False,
        ),
    ]
