# Generated by Django 4.0.4 on 2022-08-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_course_code_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
