# Generated by Django 4.0.1 on 2022-01-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_remove_timeslot_end_time_remove_timeslot_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeschedule',
            name='day',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='DaySchedule',
        ),
    ]
