# Generated by Django 4.0.1 on 2022-02-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0009_timeconfig_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeschedule',
            name='time_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slots.timeconfig'),
        ),
    ]
