# Generated by Django 4.0.1 on 2022-02-15 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slots', '0010_timeschedule_time_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeschedule',
            name='board1',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='board10',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='board2',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='board3',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='board4',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='board5',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='board6',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='board7',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='board8',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='board9',
        ),
        migrations.AddField(
            model_name='timeconfig',
            name='no_of_boards',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='timeschedule',
            name='boards',
            field=models.ManyToManyField(null=True, to='slots.Boards'),
        ),
    ]
