# Generated by Django 4.0.1 on 2022-02-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0012_alter_timeschedule_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='boards',
            name='time_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slots.timeconfig'),
        ),
        migrations.AddField(
            model_name='boards',
            name='time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slots.timeslot'),
        ),
    ]
