# Generated by Django 4.0.1 on 2022-02-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0014_rename_boards_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='time_config',
        ),
        migrations.RemoveField(
            model_name='timeschedule',
            name='boards',
        ),
        migrations.AddField(
            model_name='board',
            name='time_sched',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slots.timeschedule'),
        ),
    ]
