# Generated by Django 4.0.1 on 2022-02-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0015_remove_board_time_config_remove_timeschedule_boards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='time_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slots.timeconfig'),
        ),
    ]
