# Generated by Django 4.0.1 on 2022-04-17 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0018_board_board_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('board', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='slots.board')),
            ],
        ),
    ]
