# Generated by Django 4.0.1 on 2022-04-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0019_ipaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='board',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='board_no',
            field=models.IntegerField(default=1),
        ),
    ]
