# Generated by Django 4.0.1 on 2022-04-17 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0020_remove_ipaddress_board_ipaddress_board_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board',
            new_name='board_user',
        ),
        migrations.AddField(
            model_name='board',
            name='ip_addr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slots.ipaddress'),
        ),
    ]
