# Generated by Django 4.0.1 on 2022-04-17 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0021_rename_board_board_board_user_board_ip_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='ip_addr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slots.ipaddress'),
        ),
    ]
