# Generated by Django 4.0.1 on 2022-05-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0022_alter_board_ip_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeconfig',
            name='slot_limit',
            field=models.IntegerField(default=5),
        ),
    ]
