# Generated by Django 4.0.4 on 2022-06-09 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0023_timeconfig_slot_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeconfig',
            name='slot_limit',
        ),
    ]
