# Generated by Django 4.0.4 on 2022-06-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0024_remove_board_board_no_remove_board_time_sched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='board_serial',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
