# Generated by Django 4.0.4 on 2022-06-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0024_remove_timeconfig_slot_limit'),
        ('slots', '0025_ipaddress_board_serial'),
    ]

    operations = [
    ]
