# Generated by Django 4.0.4 on 2022-06-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0026_merge_20220613_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeconfig',
            name='slot_limit',
            field=models.IntegerField(default=5),
        ),
    ]
