# Generated by Django 4.0.4 on 2022-06-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0026_timeslot_time_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='cam_port',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
