# Generated by Django 4.0.4 on 2022-06-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0026_timeslot_time_config'),
        ('slots', '0027_timeconfig_slot_limit'),
    ]

    operations = [
    ]
