# Generated by Django 4.0.4 on 2022-07-19 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0028_remove_timeslot_time_config_board_time_sched_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='course',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='arduino_pin',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slots.timeconfig'),
        ),
    ]
