# Generated by Django 4.0.4 on 2022-07-19 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_course_code'),
        ('slots', '0029_remove_timeslot_course_ipaddress_arduino_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startday',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
