# Generated by Django 4.0.4 on 2022-07-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0028_merge_20220623_1609'),
        ('slots', '0030_alter_startday_course'),
    ]

    operations = [
    ]
