# Generated by Django 4.0.4 on 2022-05-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='staff_cred',
            field=models.BooleanField(default=False),
        ),
    ]
