# Generated by Django 4.0.4 on 2022-05-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_professors'),
        ('users', '0002_profile_courses_profile_staff_cred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
